name: release

on:
  push:
#    branches:
#      - 'release-v*'
    tags:
      - 'release-v*'

jobs:
  release:
    runs-on: ubuntu-16.04

    steps:
    - name: Check the docker version
      run: |
        docker version
        echo ${GITHUB_REF:5}