name: release

on:
  push:
#    branches:
#      - 'release-v*'
    tags:
      - 'release-v*'

jobs:
  release:
    runs-on: ubuntu-16.04

    steps:
    - name: Check the docker version
      run: |
        docker login --username=${{ secrets.ALIYUN_SHENZHEN_REGISTER_USERNAME }} registry.cn-hongkong.aliyuncs.com
        docker build --rm -t registry.cn-hongkong.aliyuncs.com/strengthening/pyanalysis:${GITHUB_REF:18} .
        docker push registry.cn-hongkong.aliyuncs.com/strengthening/pyanalysis:${GITHUB_REF:18}